services:
  generator:
    build:
      context: ./price-generator
    command: 
      ./price-generator
    env_file: 
      - price-generator/.env
    networks: 
      - price-network
  price-service:
    build:
      context: ./price-service
    command:
      ./price-service
    ports:
      - 10000:10000
    env_file: 
      - price-service/.env
    networks: 
      - price-network
  position-service:
    build:
      context: ./position-service
    command:
      ./position-service
    ports:
      - 10001:10001
    env_file: 
      - position-service/.env
    networks: 
      - price-network
  console:
    build:
      context: ./console
    command: 
      ./console
    env_file:
      - console/.env
    networks: 
      - price-network
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - postgres/.env
    networks: 
      - price-network
  redis:
    image: redis
    ports: 
      - 6379:6379  
    networks: 
      - price-network

networks:
  price-network:
    driver: bridge
